[package]
name = "game_of_life"
version = "0.1.0"
authors = ["kazinad"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7.0"
term_size="0.3.1"
num_cpus="1.10.1"
rayon="1.2.0"
